# Use the official Playwright image for Python
FROM mcr.microsoft.com/playwright/python:v1.39.0-focal

WORKDIR /app

# Copy and install Python deps
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy in all code
COPY . .

# Expose port 8000 for your Flask app
EXPOSE 8000

# By default, we will run gunicorn (the web service),
# but you can override in Render with "dockerCommand"
CMD ["gunicorn", "app:create_app()", "-b", "0.0.0.0:8000"]