services:
  - type: web
    name: flask-app
    region: frankfurt
    runtime: python
    buildCommand: "pip install -r requirements.txt && pip install playwright && playwright install chromium" 
    startCommand: "gunicorn 'app:create_app()'"
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: ENCRYPTION_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: CELERY_BROKER_URL
        fromService:
          name: celery-redis
          type: redis
          property: connectionString

  - type: worker
    name: celery-worker
    region: frankfurt
    runtime: python
    buildCommand: "pip install -r requirements.txt && pip install psycopg2-binary && pip install playwright && playwright install chromium"
    startCommand: "celery -A celery_worker worker --loglevel=info --concurrency 4"
    autoDeploy: false
    envVars:
      - key: CELERY_BROKER_URL
        fromService:
          name: celery-redis
          type: redis
          property: connectionString     
  
  - type: web
    name: flower
    region: frankfurt
    plan: free
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery flower --app celery_worker --loglevel info"
    autoDeploy: false
    envVars:
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: celery-redis
          property: connectionString

  - type: redis
    name: celery-redis
    region: frankfurt
    plan: free 
    maxmemoryPolicy: noeviction 
    ipAllowList: [] 